version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "remake"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 5
