"use client"

import {AuthCard} from "@daveyplate/better-auth-ui"

export function AuthView({pathname}: { pathname: string }) {

    return (
        <main className="flex grow flex-col items-center justify-center gap-4 p-4">
            <AuthCard pathname={pathname} redirectTo="/app" localization={{
                missingCaptchaResponse: 'Réponse CAPTCHA manquante',
                byContinuingYouAgree: 'En continuant, vous acceptez les',
                protectedByRecaptcha: 'Ce site est protégé par reCAPTCHA.',
                termsOfService: 'Conditions d’utilisation',
                privacyPolicy: 'Politique de confidentialité',
                uploadAvatar: 'Téléverser un avatar',
                passwordTooLong: 'Mot de passe trop long',
                passwordTooShort: 'Mot de passe trop court',
                sessionExpired: 'Session expirée',
                sessionNotFresh: 'Votre session n’est plus récente. Veuillez vous reconnecter.',
                passwordInvalid: 'Mot de passe invalide',
                invalidEmailOrPassword: 'Email ou mot de passe invalide',
                goBack: 'Retour',
                verifyYourEmailDescription: "Veuillez vérifier votre adresse e‑mail. Consultez votre boîte de réception pour l’email de vérification. Si vous ne l’avez pas reçu, cliquez sur le bouton ci‑dessous pour le renvoyer.",
                verifyYourEmail: 'Vérifiez votre email',
                signInUsernamePlaceholder: "Nom d’utilisateur ou email",
                usernamePlaceholder: 'Nom d’utilisateur',
                usernameInstructions: 'Max. 32 caractères.',
                usernameDescription: 'Entrez le nom d’utilisateur que vous souhaitez utiliser pour vous connecter.',
                username: 'Nom d’utilisateur',
                updatedSuccessfully: 'Mis à jour avec succès',
                unlink: 'Dissocier',
                sendVerificationCode: 'Envoyer le code de vérification',
                twoFactorTotpLabel: 'Scannez le QR Code avec votre application Authentificateur',
                twoFactorPrompt: 'Authentification à deux facteurs',
                twoFactorDisabled: "L’authentification à deux facteurs a été désactivée",
                twoFactorEnabled: "L’authentification à deux facteurs a été activée",
                twoFactorEnableInstructions: 'Veuillez entrer votre mot de passe pour activer la 2FA',
                twoFactorDisableInstructions: 'Veuillez entrer votre mot de passe pour désactiver la 2FA.',
                twoFactorCardDescription: 'Ajoutez une couche de sécurité supplémentaire à votre compte.',
                twoFactorDescription: 'Veuillez entrer votre mot de passe à usage unique pour continuer',
                twoFactorAction: 'Vérifier le code',
                twoFactor: 'Deux facteurs',
                trustDevice: 'Se souvenir de cet appareil',
                switchAccount: 'Changer de compte',
                security: 'Sécurité',
                save: 'Enregistrer',
                settings: 'Paramètres',
                setPasswordDescription: 'Cliquez sur le bouton ci‑dessous pour recevoir un email afin de définir un mot de passe.',
                setPassword: 'Définir le mot de passe',
                sessionsDescription: 'Gérez vos sessions actives et révoquez l’accès.',
                sessions: 'Sessions',
                signUpEmail: 'Vérifiez votre email pour le lien de vérification.',
                signUpDescription: 'Entrez vos informations pour créer un compte',
                signUpAction: 'Créer un compte',
                signUp: 'Inscription',
                signOut: 'Déconnexion',
                signInWith: 'Se connecter avec',
                signInUsernameDescription: 'Entrez votre nom d’utilisateur ou email ci‑dessous pour vous connecter',
                signInDescription: 'Entrez votre email ci‑dessous pour vous connecter',
                signInAction: 'Connexion',
                signIn: 'Connexion',
                apiKey: 'Clé API',
                deleteApiKeyConfirmation: 'Êtes‑vous sûr de vouloir supprimer cette clé API ?',
                deleteApiKey: 'Supprimer la clé API',
                revoke: 'Révoquer',
                requestFailed: 'Échec de la requête',
                resetPasswordSuccess: 'Mot de passe réinitialisé avec succès',
                resetPasswordInvalidToken: "Lien de réinitialisation de mot de passe invalide",
                resetPasswordDescription: 'Entrez votre nouveau mot de passe ci‑dessous',
                resetPasswordAction: 'Enregistrer le nouveau mot de passe',
                resetPassword: 'Réinitialiser le mot de passe',
                resendVerificationEmail: 'Renvoyer l’email de vérification',
                resendCode: 'Renvoyer le code',
                rememberMe: 'Se souvenir de moi',
                recoverAccountDescription: 'Veuillez entrer un code de secours pour accéder à votre compte',
                recoverAccountAction: 'Récupérer le compte',
                recoverAccount: 'Récupérer le compte',
                providersDescription: 'Connectez votre compte avec un service tiers.',
                providers: 'Fournisseurs',
                passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
                passwordRequired: 'Le mot de passe est requis',
                passwordPlaceholder: 'Mot de passe',
                password: 'Mot de passe',
                create: 'Créer',
                noExpiration: 'Sans expiration',
                expires: 'Expire',
                neverExpires: 'N’expire jamais',
                apiKeyCreatedDescription: 'Veuillez copier votre clé API et la conserver en lieu sûr. Pour des raisons de sécurité, nous ne pourrons pas l’afficher à nouveau.',
                apiKeyCreated: 'Clé API créée',
                apiKeyNamePlaceholder: 'Nouvelle clé API',
                createApiKeyDescription: 'Entrez un nom unique pour votre clé API afin de la distinguer des autres.',
                createApiKey: 'Créer une clé API',
                apiKeysInstructions: 'Générez des clés API pour accéder à votre compte par programme.',
                apiKeysDescription: 'Gérez vos clés API pour un accès sécurisé.',
                apiKeys: 'Clés API',
                passkeysInstructions: 'Accédez en toute sécurité à votre compte sans mot de passe.',
                passkeysDescription: 'Gérez vos clés de sécurité pour un accès sécurisé.',
                passkeys: 'Clés de sécurité',
                passkey: 'Clé de sécurité',
                orContinueWith: 'Ou continuez avec',
                oneTimePassword: 'Mot de passe à usage unique',
                newPasswordRequired: 'Un nouveau mot de passe est requis',
                newPasswordPlaceholder: 'Nouveau mot de passe',
                newPassword: 'Nouveau mot de passe',
                namePlaceholder: 'Nom',
                nameInstructions: 'Max. 32 caractères.',
                nameDescription: 'Veuillez entrer votre nom complet, ou un pseudonyme.',
                name: 'Nom',
                emailOTPVerificationSent: 'Veuillez vérifier votre email pour le code de vérification.',
                emailOTPDescription: 'Entrez votre email pour recevoir un code',
                emailOTPVerifyAction: 'Vérifier le code',
                emailOTPSendAction: 'Envoyer le code',
                emailOTP: 'Code par email',
                magicLinkEmail: 'Vérifiez votre email pour le lien magique',
                magicLinkDescription: 'Entrez votre email pour recevoir un lien magique',
                magicLinkAction: 'Envoyer le lien magique',
                magicLink: 'Lien magique',
                link: 'Lien',
                invalidTwoFactorCookie: 'Cookie de validation à deux facteurs invalide',
                forgotPasswordLink: 'Mot de passe oublié ?',
                forgotPasswordEmail: 'Vérifiez votre email pour le lien de réinitialisation du mot de passe.',
                forgotPasswordDescription: 'Entrez votre email pour réinitialiser votre mot de passe',
                forgotPasswordAction: 'Envoyer le lien de réinitialisation',
                forgotPassword: 'Mot de passe oublié',
                forgotAuthenticator: 'Authentificateur oublié ?',
                isTheSame: 'est identique',
                isRequired: 'est requis',
                isInvalid: 'est invalide',
                error: 'Erreur',
                enable: 'Activer',
                emailVerification: 'Veuillez vérifier votre email pour le lien de vérification.',
                emailVerifyChange: 'Veuillez vérifier votre email pour confirmer la modification.',
                emailRequired: "L'adresse email est requise",
                emailPlaceholder: 'm@example.com',
                emailIsTheSame: "L’email est identique",
                emailInvalid: "L’adresse email est invalide",
                emailInstructions: "Veuillez entrer une adresse email valide.",
                emailDescription: "Entrez l'adresse email que vous souhaitez utiliser pour vous connecter.",
                email: 'Email',
                done: 'Terminé',
                dontHaveAnAccount: 'Pas de compte ?',
                disabledCredentialsDescription: 'Choisissez un fournisseur pour vous connecter à votre compte',
                disable: 'Désactiver',
                deleteAccountNotFresh: 'Vous devez être connecté récemment pour supprimer votre compte.',
                deleteAccountSuccess: 'Votre compte a été supprimé.',
                deleteAccountVerify: 'Veuillez vérifier votre email pour confirmer la suppression de votre compte.',
                deleteAccountInstructions: 'Veuillez confirmer la suppression de votre compte. Cette action est irréversible, faites preuve de prudence.',
                deleteAccountDescription: 'Supprimez définitivement votre compte et tout son contenu. Cette action est irréversible, faites preuve de prudence.',
                deleteAccount: 'Supprimer le compte',
                deleteAvatar: 'Supprimer l’avatar',
                delete: 'Supprimer',
                currentSession: 'Session actuelle',
                currentPasswordPlaceholder: 'Mot de passe actuel',
                currentPassword: 'Mot de passe actuel',
                continue: 'Continuer',
                copyAllCodes: 'Copier tous les codes',
                copyToClipboard: 'Copier dans le presse‑papiers',
                copiedToClipboard: 'Copié dans le presse‑papiers',
                continueWithAuthenticator: 'Continuer avec un authentificateur',
                confirmPasswordRequired: 'La confirmation du mot de passe est requise',
                confirmPasswordPlaceholder: 'Confirmer le mot de passe',
                confirmPassword: 'Confirmer le mot de passe',
                changePasswordSuccess: 'Votre mot de passe a été modifié.',
                changePasswordInstructions: 'Veuillez utiliser au moins 8 caractères.',
                changePasswordDescription: 'Entrez votre mot de passe actuel et un nouveau mot de passe.',
                changePassword: 'Changer le mot de passe',
                cancel: 'Annuler',
                backupCodeAction: 'Récupérer le compte',
                backupCode: 'Code de secours',
                backupCodePlaceholder: 'Entrez un de vos codes de secours. Chaque code ne peut être utilisé qu’une seule fois et devient invalide après usage.',
                backupCodesDescription: 'Conservez ces codes de secours en lieu sûr. Vous pouvez les utiliser pour accéder à votre compte si vous perdez votre méthode d’authentification à deux facteurs.',
                backupCodes: 'Codes de secours',
                backupCodeRequired: 'Un code de secours est requis',
                avatarInstructions: 'Un avatar est optionnel mais fortement recommandé.',
                avatarDescription: 'Cliquez sur l’avatar pour téléverser un avatar personnalisé depuis vos fichiers.',
                avatar: 'Avatar',
                alreadyHaveAnAccount: 'Vous avez déjà un compte ?',
                addPasskey: 'Ajouter une clé de sécurité',
                addAccount: 'Ajouter un compte',
                accountsInstructions: 'Connectez‑vous à un compte supplémentaire.',
                accountsDescription: 'Gérez vos comptes actuellement connectés.',
                accounts: 'Comptes',
                account: 'Compte',
            }}/>
        </main>
    )
}