"use client";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faCircle} from "@fortawesome/free-solid-svg-icons";
import GifPicker from "gif-picker-react";
import {EmojiPicker, EmojiPickerContent, EmojiPickerFooter, EmojiPickerSearch,} from "@/components/ui/emoji-picker";
import {
    Check,
    ChevronsUpDown,
    CircleAlert,
    Copy,
    IdCardLanyard,
    Info,
    Laugh,
    MessageCircleOff,
    MicOff,
    NotebookPen,
    PhoneCall,
    ScanFace,
    Send,
    TvMinimalPlay,
    UserRoundPlus,
    UserRoundX,
    X
} from "lucide-react";
import React, {FormEvent, useEffect, useRef, useState} from "react";
import {formVolunteer, Msg, MsgWithID, ticketInfo} from "@/lib/interface";
import {z, ZodError} from "zod";
import {toast} from "sonner";
import {saveMessage} from "@/lib/messageManager";
import {useSession} from "@/lib/auth-client";
import {Socket} from "socket.io-client";
import {Button, Dialog, DialogContent, DialogHeader, DialogTrigger, Textarea, useSidebar} from "@/components/ui";
import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
    AlertDialogTrigger,
} from "@/components/ui/alert-dialog"
import {zodResolver} from "@hookform/resolvers/zod"
import {useForm} from "react-hook-form"
import {cn} from "@/lib/utils"
import {Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList,} from "@/components/ui/command"
import {Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage,} from "@/components/ui/form"
import {Popover, PopoverContent, PopoverTrigger,} from "@/components/ui/popover"
import type {Reaction, Ticket} from "@/generated/prisma/client"
import {useRouter} from "next/navigation";
import {Message} from "@/components/message";
import {useSocket} from "@/context/Socket";
import {usePeer} from "@/context/VoicePeer";

export function Chat(props: { channelID: string, statusID: number }) {
    const {channelID, statusID} = props;
    const [status, setStatus] = useState(statusID);
    const {data: session} = useSession();
    const {socket, setChannelID} = useSocket();
    const router = useRouter();
    const [emojiOpen, setEmojiOpen] = useState(false);
    const [ticketInfo, setTicketInfo] = useState<ticketInfo>();
    const [gifOpen, setGifOpen] = useState(false);
    const [showTyping, setShowTyping] = useState(false);
    const [ticket, setTicket] = useState<Ticket>();
    const [currentMsg, setCurrentMsg] = useState("");
    const [channelName, setChannelName] = useState("le chat");
    const [replyTo, setReplyTo] = useState<{
        id: number;
        authorName: string;
        content: string;
        timestamp: number
    } | null>(null);
    const [chat, setChat] = useState<MsgWithID[]>([])
    const formRef = useRef<HTMLFormElement>(null);
    const textRef = useRef<HTMLTextAreaElement>(null);
    const rootDivRef = useRef<HTMLDivElement>(null);
    const emojiPickerRef = useRef<HTMLDivElement>(null);
    const socketRef = useRef<Socket | null>(null);
    const messagesListRef = useRef<HTMLDivElement>(null);
    const myVideoRef = useRef<HTMLVideoElement>(null);
    const callingVideoRef = useRef<HTMLVideoElement>(null);
    // const [peerInstance, setPeerInstance] = useState<Peer | null>(null);
    const [idToCall, setIdToCall] = useState('');
    const [localStream, setLocalStream] = useState<MediaStream | null>(null);
    // const [callColor, setCallColor] = useState<string>("#000");
    const [available, setAvailable] = useState<formVolunteer[]>([]);
    const {toggleSidebar} = useSidebar();
    const myAudioRef = useRef<HTMLAudioElement>(null);
    const remoteAudioRef = useRef<HTMLAudioElement>(null);

    const messageSchema = z
        .string()
        .max(2000, "Votre message est trop long")
        .refine((val) => val.trim().length >= 1, {
            message: "Contenu du message non supporté",
        });


    const sendMessage = async (content: string) => {
        const msg: Msg = {
            author: {
                id: session?.user.id as string,
                name: session?.user.displayUsername as string || session?.user.name as string,
                image: session?.user.image as string,
                role: session?.user.role as string,
            },
            timestamp: Date.now(),
            channel: {
                id: channelID,
            },
            discordID: null,
            reactions: [],
            content,
        };

        try {
            const savedMessage = await saveMessage(msg);
            // savedMessage includes the id generated by the DB
            const msgWithID: MsgWithID = {
                ...msg,
                id: savedMessage.id,
            };

            socket?.emit("sendMessage", msgWithID);
            setChat((pre) => [...pre, msgWithID]);
        } catch (error) {
            console.error("Error saving message:", error);
            // optionally show user feedback here
        }
    };

    const sendForm = async (e: FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        try {
            messageSchema.parse(currentMsg);
        } catch (error) {
            if (error instanceof ZodError) {
                return toast.error(error.errors[0].message);
            }
        }
        if (currentMsg !== "") {
            // Optionally include reply metadata in future API
            sendMessage(currentMsg);
            setCurrentMsg("");
            setReplyTo(null);
        }
    }

    const sendTyping = async () => {
        await socket?.emit('typing', {id: channelID});
    }

    const {peerInstance, callColor, startCall, stopCall} = usePeer();

    const handleCall = () => {
        if (peerInstance) {
            stopCall();
        } else {
            startCall(myAudioRef, remoteAudioRef);
        }
    };

    type UserFromList = {
        id: string;
        username: string;
        image: string | null;
        role: string;
    };

    const [onlineUsers, setOnlineUsers] = useState<UserFromList[]>([]);


    useEffect(() => {
        if (!socket) return;

        let timer: NodeJS.Timeout;

        function handleConnect() {
            console.log('handling connection')
            if (!socket) return console.log('no socket');
            socket.emit('getOnlineUsers', {channelID}, (users: {
                id: string;
                image: string | null;
                role: string;
                username: string
            }[]) => {
                console.log('users connected', users);
                setOnlineUsers(users);
            });
        }

        handleConnect();

        function handleUserList(users: UserFromList[]) {
            console.log("Received user list:", users);
            setOnlineUsers(users);
        }

        socket.on("userList", handleUserList);

        socket.on('connect', handleConnect);

        socket.on("message", (data: Msg) => {
            if (data.channel.id === channelID) {
                setChat((pre) => [...pre, data as MsgWithID])
                if (timer) clearTimeout(timer)
            }
        });

        socket.on('typingIndicator', () => {
            setShowTyping(true);
            if (timer) clearTimeout(timer);
            timer = setTimeout(() => {
                setShowTyping(false);
            }, 5000)
        });

        socket.on('reactionAdd', (data) => {
            console.log("REACTION ADD", data);
            setChat(prev =>
                prev.map(message => {
                    if (message.id === data.messageID) {
                        // Avoid adding duplicate reactions from same user and emoji
                        const existingReactions = message.reactions ?? [];
                        const alreadyExists = existingReactions.some(
                            r => r.userID === data.userID && r.emoji === data.emoji
                        );

                        if (alreadyExists) {
                            // Optionally, replace the old reaction with the new data
                            const updatedReactions = existingReactions.map(r =>
                                r.userID === data.userID && r.emoji === data.emoji ? data : r
                            );
                            return {
                                ...message,
                                reactions: updatedReactions
                            };
                        }

                        // Add new reaction if no duplicate found
                        return {
                            ...message,
                            reactions: [...existingReactions, data]
                        };
                    }
                    return message;
                })
            );
        });

        socket.on('reactionRemove', (data) => {
            console.log("REACTION REMOVE", data);
            const {messageID, id: reactionId} = data;

            setChat(prev =>
                prev.map(message => {
                    if (message.id === messageID) {
                        const filteredReactions = (message.reactions ?? []).filter(
                            r => r.id !== reactionId
                        );

                        return {
                            ...message,
                            reactions: filteredReactions
                        };
                    }
                    return message;
                })
            );
        });

        return () => {
            socket.off('userList');
            socket.off('reactionAdd');
            socket.off('reactionRemove');
        };
    }, [socket]);

    useEffect(() => {
        fetch(`/api/messages/${channelID}`)
            .then(res => res.json())
            .then(data => {
                setChat(data)
                messagesListRef.current?.scrollIntoView()
            });
        fetch(`/api/channel/${channelID}`)
            .then(res => res.json())
            .then(data => {
                setChannelName(data.name)
            });

        console.log(status)
        if (status !== 0) {
            fetch(`/api/tickets/findBy/channelID`, {
                method: "POST",
                body: JSON.stringify({
                    channelID: channelID,
                }),
            }).then(res => res.json()).then(data => {
                try {
                    setTicket(data.ticket);
                } catch (e) {
                    console.log(e);
                }
            });
        }
        fetch(`/api/events/getAvailable`)
            .then(res => res.json())
            .then(data => {
                setAvailable([
                    ...data.map((user: { name: any; id: any; }) => ({
                        label: user.name,
                        value: {
                            id: user.id,
                            name: user.name,
                        }
                    }))
                ]);
            })
        // rootDivRef.current?.focus();

        return () => {
        }
    }, []);

    // Always scroll to bottom when chat list changes (initial load and new messages)
    useEffect(() => {
        // use smooth on subsequent updates; browsers will auto-select behavior on first paint
        messagesListRef.current?.scrollIntoView({behavior: 'smooth', block: 'end'});
    }, [chat]);

    const nonChar = [
        // Navigation
        "ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight",
        "Home", "End", "PageUp", "PageDown",

        // Control & UI
        "Escape", "Enter", "Tab",
        "ContextMenu", "PrintScreen", "Pause", "ScrollLock",

        // Modifier keys
        "Alt", "AltGraph", "CapsLock", "Control", "Fn", "FnLock",
        "Meta", "Shift", "NumLock", "Symbol", "SymbolLock", "Hyper",

        // Function keys
        "F1", "F2", "F3", "F4", "F5", "F6",
        "F7", "F8", "F9", "F10", "F11", "F12",
        "Soft1", "Soft2", "Soft3", "Soft4",

        // Editing keys
        "Clear",
        "Copy",

        // Media keys
        "MediaPlay", "MediaPause", "MediaStop",
        "MediaTrackNext", "MediaTrackPrevious", "MediaSelect",

        // Audio controls
        "VolumeMute", "VolumeDown", "VolumeUp",
        "AudioVolumeMute", "AudioVolumeDown", "AudioVolumeUp",

        // App launch
        "LaunchMail", "LaunchMediaPlayer",

        // Speech-related
        "SpeechToggle", "SpeechDictation",

        // Numpad keys (non-textual)
        "NumpadEnter",
        "NumpadAdd", "NumpadSubtract", "NumpadMultiply", "NumpadDivide",
        "NumpadDecimal",
        "NumpadEqual",
        "NumpadParenLeft", "NumpadParenRight",
        "NumpadMemoryAdd", "NumpadMemoryClear", "NumpadMemoryRecall",
        "NumpadMemoryStore", "NumpadMemorySubtract",

        // Misc
        "Help", "Insert", "Clear",

        // Unidentified
        "Unidentified"
    ];

    const FormSchema = z.object({
        volunteer: z.object({
            id: z.string({
                required_error: "Merci de sélectionner un Bénévole Écoutant",
            }),
            name: z.string(),
        }),
    });

    const form = useForm<z.infer<typeof FormSchema>>({
        resolver: zodResolver(FormSchema),
    });

    function assign(data: z.infer<typeof FormSchema>) {
        fetch(`/api/tickets/assign`, {
            method: "POST",
            body: JSON.stringify({
                ticketID: ticket?.id,
                assignmentID: data.volunteer.id
            }),
        }).then(res => res.json()).then(res => {
            if (res.success) {
                toast.success(`L'écoute à été attribuée à ${data.volunteer.name}`)
                setStatus(2)
                socket?.emit('update')
            } else {
                return toast("Erreur lors de l'attribution", {
                    description: (
                        <pre className="mt-2 w-[320px] rounded-md bg-neutral-950 p-4">
                          <code className="text-white">{JSON.stringify(res.error, null, 2)}</code>
                        </pre>
                    ),
                })
            }
        })
    }

    const transmissionSchema = z.object({
        problematic: z.string(),
        observations: z.string(),
        info: z.string().optional(),
    });

    const transmissionForm = useForm<z.infer<typeof transmissionSchema>>({
        resolver: zodResolver(transmissionSchema),
    });

    function transmission(data: z.infer<typeof transmissionSchema>) {
        fetch('/api/tickets/transmission', {
            method: "POST",
            body: JSON.stringify({
                channelID,
                problematic: data.problematic,
                observations: data.observations,
                info: data.info,
            })
        }).then(res => res.json()).then(res => {
            if (res.success) {
                toast("Transmission envoyée")
                setTimeout(() => {
                    router.push("/app/chat")
                    socket?.emit('update')
                }, 2000)
            } else {
                return toast("Erreur lors de la transmission", {
                    description: (
                        <pre className="mt-2 w-[320px] rounded-md bg-neutral-950 p-4">
                  <code className="text-white">{JSON.stringify(data, null, 2)}</code>
                </pre>
                    ),
                })
            }
        })
    }

    const roleOrderAndLabels: Record<string, string> = {
        bot: "Robot",
        admin: "Administrateur",
        manager: "Référent Bénévole Écoutant",
        volunteer: "Bénévole Écoutant",
        training: "Bénévole en formation"
    };

    return (
        <div className="flex flex-row items-center justify-center w-full">
            <div className="flex flex-col relative h-svh p-3 gap-4 w-full" tabIndex={0} ref={rootDivRef}>
                    {/*<video className='w-0 h-0' playsInline ref={callingVideoRef} autoPlay/>*/}
                    <div className="flex flex-col flex-grow overflow-y-auto mt-10">
                        {chat.map(({author, content, timestamp, reactions, id}, key) => {
                            const prevMessage = key > 0 ? chat[key - 1] : null
                            const nextMessage = key < chat.length - 1 ? chat[key + 1] : null
                            const currentDate = new Date(timestamp).getTime()
                            const prevDate = prevMessage ? new Date(prevMessage.timestamp).getTime() : null
                            const nextDate = nextMessage ? new Date(nextMessage.timestamp).getTime() : null

                            const isSameAuthorAsPrev = prevMessage && prevMessage.author.id === author.id
                            const isWithin10MinOfPrev = prevDate !== null && Math.abs(currentDate - prevDate) / 60000 < 10
                            const showAuthorInfo = !isSameAuthorAsPrev || !isWithin10MinOfPrev

                            const isSameAuthorAsNext = nextMessage && nextMessage.author.id === author.id
                            const isWithin10MinOfNext = nextDate !== null && Math.abs(nextDate - currentDate) / 60000 < 10
                            const isLastInBlock = !isSameAuthorAsNext || !isWithin10MinOfNext

                            return (
                                <Message
                                    prevDate={prevDate as number}
                                    currentDate={currentDate}
                                    timestamp={timestamp}
                                    reactions={reactions as Reaction[]}
                                    key={id}  // better: use unique id instead of array index
                                    isLastInBlock={isLastInBlock}
                                    showAuthorInfo={showAuthorInfo}
                                    isAuthor={author.id === session?.user.id}
                                    profilePicture={author.image}
                                    authorRole={author.role}
                                    authorName={author.name}
                                    content={content}
                                    userID={session?.user.id as string}
                                    id={id as number}
                                    channelId={channelID}
                                    onReply={({id, authorName, content, timestamp}) => {
                                        setReplyTo({id, authorName, content, timestamp});
                                        // Focus input for quick replying
                                        setTimeout(() => textRef.current?.focus(), 0);
                                    }}
                                    replyTargetId={replyTo?.id}
                                />
                            );
                        })}
                        <div ref={messagesListRef} className="h-px"/>
                    </div>


                    <div className={showTyping ? 'flex flex-row gap-1 relative left-2 bottom-3' : 'hidden'}>
                        <FontAwesomeIcon icon={faCircle} className="text-gray-400 animate-opacityPulse1"/>
                        <FontAwesomeIcon icon={faCircle} className="text-gray-400 animate-opacityPulse2"/>
                        <FontAwesomeIcon icon={faCircle} className="text-gray-400 animate-opacityPulse3"/>
                    </div>

                    {
                        status === 0 ? null :
                            <div className="absolute top-6 right-6 flex flex-row gap-2">
                                <AlertDialog>
                                    <AlertDialogTrigger asChild>
                                        <Button
                                            className={channelID == "1" || status == 3 || status == 4 ? "hidden" : "flex"}
                                            variant="outline" disabled={status == 3 || status == 4}>
                                            <UserRoundPlus/> Attribuer
                                        </Button>
                                    </AlertDialogTrigger>
                                    <AlertDialogContent>
                                        <AlertDialogHeader>
                                            <AlertDialogTitle>Merci de choisir le bénévole à
                                                attribuer</AlertDialogTitle>
                                        </AlertDialogHeader>
                                        <Form {...form}>
                                            <form onSubmit={form.handleSubmit(assign)} className="space-y-6">
                                                <FormField
                                                    control={form.control}
                                                    name="volunteer"
                                                    render={({field}) => (
                                                        <FormItem className="flex flex-col">
                                                            <FormLabel>Bénévole Écoutant</FormLabel>
                                                            <Popover>
                                                                <PopoverTrigger asChild>
                                                                    <FormControl>
                                                                        <Button
                                                                            variant="outline"
                                                                            role="combobox"
                                                                            className={cn(
                                                                                "w-[350px] justify-between",
                                                                                !field.value && "text-muted-foreground"
                                                                            )}
                                                                        >
                                                                            {field.value
                                                                                ? available.find(
                                                                                    (available) => available.value.name === field.value.name
                                                                                )?.label
                                                                                : "Sélectionner le bénévole"}
                                                                            <ChevronsUpDown className="opacity-50"/>
                                                                        </Button>
                                                                    </FormControl>
                                                                </PopoverTrigger>
                                                                <PopoverContent className="w-[350px] p-0">
                                                                    <Command>
                                                                        <CommandInput
                                                                            placeholder="Rechercher un bénévole..."
                                                                            className="h-9"
                                                                        />
                                                                        <CommandList>
                                                                            <CommandEmpty>Aucun bénévole
                                                                                trouvé</CommandEmpty>
                                                                            <CommandGroup>
                                                                                {available.map((available) => (
                                                                                    <CommandItem
                                                                                        value={available.label}
                                                                                        key={available.value.id}
                                                                                        onSelect={() => {
                                                                                            form.setValue("volunteer", available.value)
                                                                                        }}
                                                                                    >
                                                                                        {available.label}
                                                                                        <Check
                                                                                            className={cn(
                                                                                                "ml-auto",
                                                                                                available.value === field.value
                                                                                                    ? "opacity-100"
                                                                                                    : "opacity-0"
                                                                                            )}
                                                                                        />
                                                                                    </CommandItem>
                                                                                ))}
                                                                            </CommandGroup>
                                                                        </CommandList>
                                                                    </Command>
                                                                </PopoverContent>
                                                            </Popover>
                                                            <FormDescription>
                                                                Le bénévole aura ensuite accès à l'écoute
                                                            </FormDescription>
                                                            <FormMessage/>
                                                        </FormItem>
                                                    )}
                                                />

                                                <AlertDialogFooter>
                                                    <AlertDialogCancel>Annuler</AlertDialogCancel>
                                                    <AlertDialogAction asChild>
                                                        <Button type="submit">Valider</Button>
                                                    </AlertDialogAction>
                                                </AlertDialogFooter>
                                            </form>
                                        </Form>
                                    </AlertDialogContent>
                                </AlertDialog>

                                <Button
                                    className={channelID == "1" || status !== 2 ? "hidden" : "flex"}
                                    variant='outline'
                                    color={callColor}
                                    onClick={handleCall}
                                    disabled={status !== 2}
                                >
                                    <PhoneCall color={callColor}/> Démarrer un vocal
                                    <audio ref={myAudioRef} autoPlay
                                           muted/>  {/* my own voice (muted so I don't hear myself) */}
                                    <audio ref={remoteAudioRef} autoPlay/>
                                    {/* the other user's audio */}
                                </Button>

                                <AlertDialog>
                                    <AlertDialogTrigger asChild>
                                        <Button
                                            className={channelID == "1" || status == 3 || status == 4 ? "hidden" : "flex"}
                                            variant="destructive" disabled={status == 3 || status == 4}>
                                            <MessageCircleOff/> Fermer l'écoute
                                        </Button>
                                    </AlertDialogTrigger>
                                    <AlertDialogContent>
                                        <AlertDialogHeader>
                                            <AlertDialogTitle>Attention, êtes vous certain ?</AlertDialogTitle>
                                            <AlertDialogDescription>
                                                La fermeture d'une écoute est irréversible. Pour simplement retourner au
                                                chat de
                                                permanence merci d'utiliser l'onglet latéral.
                                            </AlertDialogDescription>
                                        </AlertDialogHeader>
                                        <AlertDialogFooter>
                                            <AlertDialogCancel>Annuler</AlertDialogCancel>
                                            <AlertDialogAction asChild>
                                                <Button variant="destructive" onClick={() => {
                                                    fetch('/api/tickets/close', {
                                                        method: 'POST',
                                                        body: JSON.stringify({
                                                            channelID: channelID
                                                        })
                                                    }).then(res => res.json()).then(res => {
                                                        if (res.success) {
                                                            setStatus(3)
                                                        }
                                                    })
                                                }}>
                                                    Fermer l'écoute
                                                </Button>
                                            </AlertDialogAction>
                                        </AlertDialogFooter>
                                    </AlertDialogContent>
                                </AlertDialog>

                                <AlertDialog>
                                    <AlertDialogTrigger asChild>
                                        <Button className={channelID == "1" || status !== 3 ? "hidden" : "flex"}
                                                variant="outline" disabled={status !== 3}>
                                            <NotebookPen/> Transmission
                                        </Button>
                                    </AlertDialogTrigger>
                                    <AlertDialogContent>
                                        <AlertDialogHeader>
                                            <AlertDialogTitle>Merci de remplir la fiche de
                                                transmission</AlertDialogTitle>
                                        </AlertDialogHeader>
                                        <Form {...transmissionForm}>
                                            <form onSubmit={transmissionForm.handleSubmit(transmission)}
                                                  className="space-y-6">
                                                <FormField
                                                    control={transmissionForm.control}
                                                    name="problematic"
                                                    render={({field}) => (
                                                        <FormItem className="flex flex-col">
                                                            <FormLabel>Problématique de l'écoute* :</FormLabel>
                                                            <FormControl>
                                                                <Textarea
                                                                    placeholder="Problématique..."
                                                                    className="resize-none"
                                                                    {...field}
                                                                />
                                                            </FormControl>
                                                            <FormMessage/>
                                                        </FormItem>
                                                    )}
                                                />
                                                <FormField
                                                    control={transmissionForm.control}
                                                    name="observations"
                                                    render={({field}) => (
                                                        <FormItem className="flex flex-col">
                                                            <FormLabel>Observations générales* :</FormLabel>
                                                            <FormControl>
                                                                <Textarea
                                                                    placeholder="Observations..."
                                                                    className="resize-none"
                                                                    {...field}
                                                                />
                                                            </FormControl>
                                                            <FormMessage/>
                                                        </FormItem>
                                                    )}
                                                />
                                                <FormField
                                                    control={transmissionForm.control}
                                                    name="info"
                                                    render={({field}) => (
                                                        <FormItem className="flex flex-col">
                                                            <FormLabel>Informations supplémentaires (optionnel)
                                                                :</FormLabel>
                                                            <FormControl>
                                                                <Textarea
                                                                    placeholder="Informations..."
                                                                    className="resize-none"
                                                                    {...field}
                                                                />
                                                            </FormControl>
                                                            <FormMessage/>
                                                        </FormItem>
                                                    )}
                                                />

                                                <AlertDialogFooter>
                                                    <AlertDialogCancel>Annuler</AlertDialogCancel>
                                                    <AlertDialogAction asChild>
                                                        <Button type="submit">Envoyer</Button>
                                                    </AlertDialogAction>
                                                </AlertDialogFooter>
                                            </form>
                                        </Form>
                                    </AlertDialogContent>
                                </AlertDialog>

                                <Dialog>
                                    <DialogTrigger asChild>
                                        <Button variant="outline">
                                            <Info/>
                                        </Button>
                                    </DialogTrigger>
                                    <DialogContent className="w-[1000px]">
                                        <DialogHeader>
                                            {/*<DialogTitle>Informations de l'écoute</DialogTitle>*/}
                                            {/*<DialogDescription>*/}
                                            <h4 className="scroll-m-20 text-xl font-semibold tracking-tight flex flex-row gap-3">
                                                <CircleAlert/> Vigilances
                                            </h4>
                                            <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
                                                {
                                                    ticketInfo?.vigis.length && ticketInfo.vigis.length > 0 ?
                                                        ticketInfo?.vigis.map((item, index) => (
                                                            <li key={index}>{item.date.toLocaleDateString()} - {item.motive}</li>
                                                        )) : <li>Aucune vigilance en cours</li>
                                                }
                                            </ul>

                                            <h4 className="scroll-m-20 text-xl font-semibold tracking-tight flex flex-row gap-3">
                                                <UserRoundX/> Bénévoles Inéligibles
                                            </h4>
                                            <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
                                                <li>Anthony J</li>
                                                <li>Julie R</li>
                                                <li>Paul PR</li>
                                            </ul>

                                            <h4 className="scroll-m-20 text-xl font-semibold tracking-tight flex flex-row gap-3">
                                                <MicOff/> Bénévoles Inéligibles Vocal
                                            </h4>
                                            <ul className="my-6 ml-6 list-disc [&>li]:mt-2">
                                                <li>Anthony J</li>
                                                <li>Julie R</li>
                                                <li>Paul PR</li>
                                            </ul>

                                            <h4 className="scroll-m-20 text-xl font-semibold tracking-tight flex flex-row gap-3">
                                                <IdCardLanyard/> Identifiant
                                            </h4>
                                            <p className="leading-7 [&:not(:first-child)]:mt-6">
                                                Numéro d'anonymat : 277dd0... <Button variant="secondary">
                                                <Copy/> Copier</Button>
                                            </p>
                                            <p className="leading-7 [&:not(:first-child)]:mt-6">
                                                Identifiant Discord : <Button variant="secondary">
                                                <ScanFace/> Révéler</Button>
                                            </p>

                                            {/*</DialogDescription>*/}
                                        </DialogHeader>
                                    </DialogContent>
                                </Dialog>
                            </div>
                    }

                    <div className="sticky bottom-0">
                        {replyTo && (
                            <div
                                className="flex items-start justify-between gap-2 mb-2 p-2 rounded-md border border-blue-300 bg-blue-50 text-blue-900">
                                <div className="flex flex-col text-sm">
                                    <span className="font-medium">Répondre à {replyTo.authorName}</span>
                                    <span className="truncate max-w-[70vw] text-blue-800">{replyTo.content}</span>
                                </div>
                                <Button variant="ghost" size="icon" onClick={() => setReplyTo(null)}
                                        aria-label="Annuler la réponse">
                                    <X/>
                                </Button>
                            </div>
                        )}
                        <form ref={formRef} onSubmit={(e) => sendForm(e)}
                              className='flex flex-row w-full gap-2 items-center'>
                            <Textarea
                                placeholder={`Envoyer un message dans ${channelName}`}
                                onChange={(e) => {
                                    setCurrentMsg(e.target.value)
                                    sendTyping()
                                }}
                                disabled={status == 3 || status == 4}
                                ref={textRef}
                                onKeyDown={(e) => {
                                    if (e.key === "Enter" && !e.shiftKey) {
                                        e.preventDefault();
                                        formRef.current?.requestSubmit();
                                    }
                                }}
                                spellCheck="true"
                                data-ms-editor="true"
                                value={currentMsg}
                                className="w-full flex flex-row outline-main outline-1 p-2 rounded-lg resize-none"
                            />

                            <Popover onOpenChange={setEmojiOpen} open={emojiOpen}>
                                <PopoverTrigger asChild>
                                    <Button variant="ghost" size="icon" disabled={status == 3 || status == 4}>
                                        <Laugh/>
                                    </Button>
                                </PopoverTrigger>
                                <PopoverContent className="w-fit p-0">
                                    <EmojiPicker
                                        className="h-[342px]"
                                        onEmojiSelect={({emoji}) => {
                                            if (currentMsg.length > 0) setCurrentMsg(currentMsg + ' ' + emoji);
                                            else setCurrentMsg(emoji);
                                            setEmojiOpen(false);
                                            textRef.current?.focus();
                                            console.log(emoji);
                                        }}
                                        locale="fr"
                                    >
                                        <EmojiPickerSearch/>
                                        <EmojiPickerContent/>
                                        <EmojiPickerFooter/>
                                    </EmojiPicker>
                                </PopoverContent>
                            </Popover>

                            <Popover onOpenChange={setGifOpen} open={gifOpen}>
                                <PopoverTrigger asChild>
                                    <Button variant="ghost" size="icon" disabled={status == 3 || status == 4}>
                                        <TvMinimalPlay/>
                                    </Button>
                                </PopoverTrigger>
                                <PopoverContent className="w-fit p-0">
                                    <GifPicker tenorApiKey={process.env.NEXT_PUBLIC_TENOR_KEY as string}
                                               onGifClick={(gif) => {
                                                   sendMessage(gif.url)
                                                   setGifOpen(false);
                                               }}/>
                                </PopoverContent>
                            </Popover>

                            <Button variant="ghost" size="icon" disabled={status == 3 || status == 4}>
                                <Send/>
                            </Button>
                            {/*<button className='cursor-pointer'><Send width={42}/></button>*/}
                        </form>
                    </div>
                </div>

            <div className="hidden lg:flex flex-col justify-start h-svh w-80 p-6 gap-3 border-l-main border-l">
                <div>
                        <h3 className="scroll-m-20 text-2xl font-semibold tracking-tight">{channelName}</h3>
                    <small className="text-sm leading-none font-medium">
                        {onlineUsers.length} utilisateur{onlineUsers.length >= 2 ? "s" : null} connecté{onlineUsers.length >= 2 ? "s" : null}
                    </small>
                </div>
                <div className="flex flex-col">
                        {Object.entries(
                            onlineUsers.reduce((acc, user) => {
                                if (!acc[user.role]) acc[user.role] = [];
                                acc[user.role].push(user);
                                return acc;
                            }, {} as Record<string, typeof onlineUsers>)
                        ).sort(
                            ([roleA], [roleB]) =>
                                Object.keys(roleOrderAndLabels).indexOf(roleA) -
                                Object.keys(roleOrderAndLabels).indexOf(roleB)
                        ).map(([role, users]) => (
                            <div key={role} className="mb-4">
                                <h4 className="text-md font-semibold text-gray-700 mb-2 capitalize">
                                    {roleOrderAndLabels[role] || role}
                                </h4>
                                <div className="flex flex-col gap-2">
                                    {users.map(user => (
                                        <div
                                            key={user.id}
                                            className="flex items-center gap-2 p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700"
                                        >
                                            <img
                                                src={user.image || "/logo.svg"}
                                                alt={user.username}
                                                className="w-8 h-8 rounded-lg object-cover"
                                            />
                                            <span className="text-sm text-gray-900 dark:text-gray-100 truncate">
                                        {user.username}
                                      </span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ))}
                </div>
            </div>
        </div>
    );
}